services:
  application:
    build: .
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: farm_repository
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge